from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.worksheet.table import Table, TableStyleInfo


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "templates" / "soc_mapping_metrics_review_v7.xlsx"


SHEETS: dict[str, list[list[object]]] = {
    "instructions": [
        ["SoC Mapping + Metrics Review Workbook v7"],
        ["Purpose", "Review a compact early-stage data model: logical_components stays focused on hierarchy and logical instance count, physical_partitions describe logical-to-die partitioning plus physical count, and metrics carries all quantitative/details data."],
        [""],
        ["Sheet", "Meaning"],
        ["module_definitions", "Reusable RTL/IP/block master definitions."],
        ["logical_components", "Architecture-level logical hierarchy. Repeated use is represented by logical_instance_count."],
        ["physical_partitions", "Minimal physical partition table from logical components to scenario/tier placement. Ratio is logical content share; physical_instance_count shows how many physical copies are realized there. Details live in metrics."],
        ["metrics", "Unified metric table. Metrics can attach to logical_component, physical_partition, tier, or scenario."],
        ["metric_dictionary", "Allowed metric names, value types, units, categories, and applicable subject types."],
        ["coverage_checks", "Review helper showing whether physical partition rows close against logical counts and ratios."],
        [""],
        ["Design Rules"],
        ["1", "Do not expand logical components into _0/_1/_2 rows for repeated instances."],
        ["2", "Use physical_instance_count to show how many physical copies this partition realizes on the tier."],
        ["3", "Use partition_ratio to describe how much logical content is carried by the partition. For a repeated full module, ratio can be physical_instance_count / logical_instance_count."],
        ["4", "If one logical module is split across dies, create multiple physical_partitions with the same logical_component_id."],
        ["5", "Keep logical_components compact. Store signal count and area breakdowns as logical_component metrics."],
        ["6", "For early-stage logical area, use logic_area, sram_area, and block_area only."],
        ["7", "Do not store shape/width/height/utilization/orientation directly in physical_partitions at this stage; use metrics when needed."],
    ],
    "module_definitions": [
        ["id", "name", "module_type", "ip_owner", "reuse_class", "description"],
        ["MD_NPU_MAC", "NPU_MAC_ARRAY", "rtl_block", "AI Team", "replicated", "MAC array tile reused multiple times under NPU_TOP."],
        ["MD_NPU_SRAM", "NPU_SRAM_BANK", "memory_macro", "Memory Team", "compiler_macro", "SRAM bank generated by memory compiler."],
        ["MD_GPU_TOP", "GPU_TOP", "subsystem", "GPU Team", "partitionable", "GPU subsystem that may be partitioned across logic and memory tiers."],
        ["MD_DDR_PHY", "DDR_PHY", "phy_analog", "PHY Team", "fixed_hard_macro", "DDR PHY hard macro with edge constraints."],
    ],
    "projects": [
        ["id", "name", "product_family", "generation", "owner", "phase"],
        ["P001", "Mobile SoC Gen-A", "Flagship Mobile SoC", "Gen-A", "Architecture Team", "Architecture Planning"],
    ],
    "scenarios": [
        ["id", "project_id", "name", "scenario_type", "process_combo", "status"],
        ["S2", "P001", "3DIC Option A", "3 tiers W2W", "N5 + N7 + N7", "High"],
    ],
    "tiers": [
        ["id", "scenario_id", "tier_index", "name", "process_id", "role", "orientation", "area_limit_mm2"],
        ["T0", "S2", 0, "Top Tier", "PN5", "High-performance logic", "Face-down", 28.2],
        ["T1", "S2", 1, "Middle Tier", "PN7", "Memory + medium logic", "Face-up / Face-to-face", 31.4],
        ["T2", "S2", 2, "Bottom Tier", "PN7", "IO / PHY / PDN / logic", "Backside PDN", 15.0],
    ],
    "logical_components": [
        ["id", "project_id", "parent_id", "module_definition_id", "name", "instance_type", "resource_type", "function_domain", "hierarchy_path", "logical_instance_count", "description"],
        ["B0", "P001", "", "", "SOC_TOP", "top", "mixed", "SoC", "SOC_TOP", 1, "Logical SoC root."],
        ["B3", "P001", "B0", "", "NPU_TOP", "subsystem", "logic+memory", "AI", "SOC_TOP/NPU_TOP", 1, "NPU subsystem containing repeated MAC and SRAM modules."],
        ["B30", "P001", "B3", "MD_NPU_MAC", "NPU_MAC_ARRAY", "block", "logic", "AI Compute", "SOC_TOP/NPU_TOP/NPU_MAC_ARRAY", 4, "Logical MAC array module. Repetition is captured by logical_instance_count."],
        ["B8", "P001", "B3", "MD_NPU_SRAM", "NPU_SRAM_BANK", "macro_group", "memory", "AI Memory", "SOC_TOP/NPU_TOP/NPU_SRAM_BANK", 2, "Logical SRAM bank module."],
        ["B2", "P001", "B0", "MD_GPU_TOP", "GPU_TOP", "subsystem", "logic+memory", "Graphics", "SOC_TOP/GPU_TOP", 1, "GPU logical module may be partially partitioned across tiers."],
        ["B5", "P001", "B0", "MD_DDR_PHY", "DDR_PHY", "phy", "phy_analog", "Memory IO", "SOC_TOP/DDR_PHY", 1, "Fixed bottom-tier PHY."],
    ],
    "physical_partitions": [
        ["id", "scenario_id", "logical_component_id", "tier_id", "partition_name", "partition_type", "physical_instance_count", "partition_ratio", "description"],
        ["PP_NPU_MAC_T0_TALL", "S2", "B30", "T0", "NPU_MAC_TOP_TALL", "full", 1, 0.25, "One of four logical NPU_MAC_ARRAY copies is implemented as this top-tier physical partition. Shape details live in metrics if needed."],
        ["PP_NPU_MAC_T0_WIDE", "S2", "B30", "T0", "NPU_MAC_TOP_WIDE", "full", 1, 0.25, "A second NPU_MAC_ARRAY copy is implemented on the same top tier, but can use a different physical shape metric."],
        ["PP_NPU_MAC_T1_STD", "S2", "B30", "T1", "NPU_MAC_MID_STD", "full", 2, 0.50, "Two of four NPU_MAC_ARRAY copies are implemented by this middle-tier partition style."],
        ["PP_NPU_SRAM_T1", "S2", "B8", "T1", "NPU_SRAM_BANK_MID", "full", 2, 1.00, "Both logical SRAM bank copies are carried by this middle-tier partition."],
        ["PP_GPU_LOGIC_T0", "S2", "B2", "T0", "GPU_SHADER_LOGIC_TOP", "partial", 1, 0.65, "GPU logic-side partition on top tier. Logic/SRAM/block area details live in metrics."],
        ["PP_GPU_CACHE_T1", "S2", "B2", "T1", "GPU_CACHE_SRAM_MID", "partial", 1, 0.35, "GPU cache/SRAM-side partition on middle tier. Logic/SRAM/block area details live in metrics."],
        ["PP_NPU_TOP_GLUE_T0", "S2", "B3", "T0", "NPU_TOP_GLUE", "partial", 1, 1.00, "Parent glue/control/interconnect should be modeled as a logical residual child in the current schema."],
        ["PP_DDR_PHY_T2", "S2", "B5", "T2", "DDR_PHY_BOTTOM", "full", 1, 1.00, "Fixed PHY partition on bottom tier."],
    ],
    "metrics": [
        ["id", "scenario_id", "subject_type", "subject_id", "metric_name", "metric_value", "metric_unit", "metric_category", "value_type", "corner", "workload", "confidence", "source_note", "created_at"],
        ["M_LOG_B30_SIGNALS", "S2", "logical_component", "B30", "signal_count_total", 44, "count", "logical", "number", "typical", "nominal", "draft", "Total logical signal count. Input/output/inout are intentionally not split in phase 1.", "2026-05-27"],
        ["M_LOG_B30_LOGIC_AREA", "S2", "logical_component", "B30", "logic_area", 10.6, "mm2", "logical_area", "number", "typical", "nominal", "draft", "Logic area estimate for all four MAC instances.", "2026-05-27"],
        ["M_LOG_B30_SRAM_AREA", "S2", "logical_component", "B30", "sram_area", 0.0, "mm2", "logical_area", "number", "typical", "nominal", "draft", "SRAM area estimate for all four MAC instances.", "2026-05-27"],
        ["M_LOG_B30_BLOCK_AREA", "S2", "logical_component", "B30", "block_area", 11.8, "mm2", "logical_area", "number", "typical", "nominal", "draft", "Block area estimate including logic, SRAM, and early overhead.", "2026-05-27"],
        ["M_LOG_B8_SIGNALS", "S2", "logical_component", "B8", "signal_count_total", 24, "count", "logical", "number", "typical", "nominal", "draft", "Total logical signal count for SRAM bank module.", "2026-05-27"],
        ["M_LOG_B8_LOGIC_AREA", "S2", "logical_component", "B8", "logic_area", 0.2, "mm2", "logical_area", "number", "typical", "nominal", "draft", "Peripheral/control logic area.", "2026-05-27"],
        ["M_LOG_B8_SRAM_AREA", "S2", "logical_component", "B8", "sram_area", 7.6, "mm2", "logical_area", "number", "typical", "nominal", "draft", "SRAM macro area estimate.", "2026-05-27"],
        ["M_LOG_B8_BLOCK_AREA", "S2", "logical_component", "B8", "block_area", 8.2, "mm2", "logical_area", "number", "typical", "nominal", "draft", "Block area estimate including early overhead.", "2026-05-27"],
        ["M_PART_MAC_T0_TALL_LOGIC_AREA", "S2", "physical_partition", "PP_NPU_MAC_T0_TALL", "logic_area", 2.8, "mm2", "implementation_area", "number", "typical", "nominal", "review", "Implementation-level logic area for this physical partition.", "2026-05-27"],
        ["M_PART_MAC_T0_TALL_SHAPE", "S2", "physical_partition", "PP_NPU_MAC_T0_TALL", "shape_type", "tall_rectangle", "", "physical_shape", "text", "typical", "nominal", "draft", "Optional shape descriptor, kept out of physical_partitions.", "2026-05-27"],
        ["M_PART_MAC_T0_WIDE_SHAPE", "S2", "physical_partition", "PP_NPU_MAC_T0_WIDE", "shape_type", "wide_rectangle", "", "physical_shape", "text", "typical", "nominal", "draft", "Same logical module and die, different shape metric.", "2026-05-27"],
        ["M_PART_MAC_T1_LOGIC_AREA", "S2", "physical_partition", "PP_NPU_MAC_T1_STD", "logic_area", 6.2, "mm2", "implementation_area", "number", "typical", "nominal", "review", "Implementation logic area for this middle-tier partition.", "2026-05-27"],
        ["M_PART_GPU_LOGIC_LOGIC_AREA", "S2", "physical_partition", "PP_GPU_LOGIC_T0", "logic_area", 12.0, "mm2", "implementation_area", "number", "typical", "nominal", "draft", "Logic-side area for GPU top-tier partition.", "2026-05-27"],
        ["M_PART_GPU_CACHE_SRAM_AREA", "S2", "physical_partition", "PP_GPU_CACHE_T1", "sram_area", 6.7, "mm2", "implementation_area", "number", "typical", "nominal", "draft", "SRAM/cache-side area for GPU middle-tier partition.", "2026-05-27"],
        ["M_PART_GPU_LOGIC_POWER", "S2", "physical_partition", "PP_GPU_LOGIC_T0", "power", 3.6, "W", "power", "number", "typical", "peak", "draft", "Power estimate for GPU logic partition.", "2026-05-27"],
        ["M_TIER_T0_POWER", "S2", "tier", "T0", "power", 7.6, "W", "power", "number", "typical", "peak", "draft", "Tier-level rollup or target.", "2026-05-27"],
        ["M_SCENARIO_AREA", "S2", "scenario", "S2", "area", 74.6, "mm2", "physical", "number", "typical", "nominal", "draft", "Scenario-level summary estimate.", "2026-05-27"],
    ],
    "metric_dictionary": [
        ["metric_name", "value_type", "default_unit", "metric_category", "applies_to_subject_types", "description"],
        ["signal_count_total", "number", "count", "logical", "logical_component", "Total signal count for the logical module. Phase 1 does not split input/output/inout."],
        ["logic_area", "number", "mm2", "logical_area", "logical_component", "Logical module logic-only area estimate."],
        ["sram_area", "number", "mm2", "logical_area", "logical_component", "Logical module SRAM-only area estimate."],
        ["block_area", "number", "mm2", "logical_area", "logical_component", "Logical module total block area estimate, including early overhead."],
        ["area", "number", "mm2", "physical", "tier,scenario", "Tier or scenario area estimate. Logical modules and physical partitions use logic_area/sram_area/block_area."],
        ["power", "number", "W", "power", "logical_component,physical_partition,tier,scenario", "Power estimate."],
        ["memoryMb", "number", "Mb", "memory", "logical_component,physical_partition", "Memory capacity."],
        ["shape_type", "text", "", "physical_shape", "physical_partition", "Optional early shape descriptor, not a required partition column."],
        ["width_mm", "number", "mm", "physical_shape", "physical_partition", "Optional width metric when floorplan detail becomes available."],
        ["height_mm", "number", "mm", "physical_shape", "physical_partition", "Optional height metric when floorplan detail becomes available."],
        ["utilization", "number", "%", "physical", "physical_partition,tier", "Optional utilization estimate."],
    ],
    "relationship_examples": [
        ["Question", "How v7 represents it"],
        ["Logic does not expand repeated instances", "logical_components has one B30 NPU_MAC_ARRAY row with logical_instance_count=4."],
        ["Physical count is explicit", "physical_partitions maps B30 into physical_instance_count 1 + 1 + 2 = 4 across T0/T0/T1."],
        ["Logical table stays compact", "Signal count and logical area breakdowns live in metrics with subject_type=logical_component."],
        ["Logical area uses three explicit metrics", "logic_area, sram_area, and block_area avoid ambiguous overlap with implementation-level area."],
        ["Physical partition ratio is simple", "B30 NPU_MAC_ARRAY maps to three physical_partitions with ratios 0.25, 0.25, and 0.50, matching 1/4, 1/4, and 2/4 physical counts."],
        ["Same die has different physical styles", "PP_NPU_MAC_T0_TALL and PP_NPU_MAC_T0_WIDE are two partition rows; shape details are optional metrics."],
        ["One logical module is partitioned across dies", "B2 GPU_TOP maps to PP_GPU_LOGIC_T0 and PP_GPU_CACHE_T1 with partition_ratio 0.65 and 0.35."],
        ["Residual subsystem partition", "B3 NPU_TOP can have PP_NPU_TOP_RESIDUAL_T0 for glue/control/interconnect not represented by child modules."],
        ["Metrics avoid overlap", "The same metric_name can appear at logical_component, physical_partition, tier, or scenario level; subject_type defines meaning."],
    ],
    "coverage_checks": [
        ["scenario_id", "logical_component_id", "logical_name", "logical_instance_count", "sum_physical_instance_count", "sum_partition_ratio", "count_status", "ratio_status", "note"],
        ["S2", "B30", "NPU_MAC_ARRAY", 4, '=SUMIFS(physical_partitions!$G$2:$G$100,physical_partitions!$B$2:$B$100,A2,physical_partitions!$C$2:$C$100,B2)', '=SUMIFS(physical_partitions!$H$2:$H$100,physical_partitions!$B$2:$B$100,A2,physical_partitions!$C$2:$C$100,B2)', '=IF(D2=E2,"OK","CHECK")', '=IF(ABS(F2-1)<0.0001,"OK","CHECK")', "Repeated full module: four logical copies are realized as 1 + 1 + 2 physical copies across tiers."],
        ["S2", "B8", "NPU_SRAM_BANK", 2, '=SUMIFS(physical_partitions!$G$2:$G$100,physical_partitions!$B$2:$B$100,A3,physical_partitions!$C$2:$C$100,B3)', '=SUMIFS(physical_partitions!$H$2:$H$100,physical_partitions!$B$2:$B$100,A3,physical_partitions!$C$2:$C$100,B3)', '=IF(D3=E3,"OK","CHECK")', '=IF(ABS(F3-1)<0.0001,"OK","CHECK")', "Two SRAM bank copies are both implemented on T1."],
        ["S2", "B2", "GPU_TOP", 1, '=SUMIFS(physical_partitions!$G$2:$G$100,physical_partitions!$B$2:$B$100,A4,physical_partitions!$C$2:$C$100,B4)', '=SUMIFS(physical_partitions!$H$2:$H$100,physical_partitions!$B$2:$B$100,A4,physical_partitions!$C$2:$C$100,B4)', '=IF(D4=E4,"OK","CHECK")', '=IF(ABS(F4-1)<0.0001,"OK","CHECK")', "Single logical subsystem split by content ratio across two tiers."],
        ["S2", "B3", "NPU_TOP", 1, '=SUMIFS(physical_partitions!$G$2:$G$100,physical_partitions!$B$2:$B$100,A5,physical_partitions!$C$2:$C$100,B5)', '=SUMIFS(physical_partitions!$H$2:$H$100,physical_partitions!$B$2:$B$100,A5,physical_partitions!$C$2:$C$100,B5)', '=IF(D5=E5,"OK","CHECK")', '=IF(ABS(F5-1)<0.0001,"OK","CHECK")', "Residual parent partition only covers glue/control not represented by child rows."],
        ["S2", "B5", "DDR_PHY", 1, '=SUMIFS(physical_partitions!$G$2:$G$100,physical_partitions!$B$2:$B$100,A6,physical_partitions!$C$2:$C$100,B6)', '=SUMIFS(physical_partitions!$H$2:$H$100,physical_partitions!$B$2:$B$100,A6,physical_partitions!$C$2:$C$100,B6)', '=IF(D6=E6,"OK","CHECK")', '=IF(ABS(F6-1)<0.0001,"OK","CHECK")', "Fixed PHY has one logical copy and one physical partition."],
    ],
}


VALIDATION_LISTS = {
    "partition_type": ["full", "partial"],
    "subject_type": ["logical_component", "physical_partition", "tier", "scenario"],
    "value_type": ["number", "text", "boolean"],
    "confidence": ["approved", "review", "draft"],
}


def style_sheet(ws) -> None:
    header_fill = PatternFill("solid", fgColor="0F172A")
    header_font = Font(color="FFFFFF", bold=True)
    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(vertical="center", wrap_text=True)
    for column in ws.columns:
        max_len = max(len(str(cell.value or "")) for cell in column)
        ws.column_dimensions[column[0].column_letter].width = min(max(max_len + 2, 12), 44)
    for row in ws.iter_rows():
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
    ws.freeze_panes = "A2"
    ws.sheet_view.showGridLines = False
    if ws.max_row > 1 and ws.max_column > 1:
        ws.auto_filter.ref = ws.dimensions


def add_table(ws, name: str) -> None:
    if ws.max_row <= 1 or ws.max_column <= 1:
        return
    headers = [cell.value for cell in ws[1]]
    if any(not isinstance(header, str) or not header for header in headers):
        return
    table = Table(displayName=f"{name}_table", ref=ws.dimensions)
    table.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True, showColumnStripes=False)
    ws.add_table(table)


def add_list_validation(ws, range_address: str, values: list[str]) -> None:
    validation = DataValidation(type="list", formula1='"' + ",".join(values) + '"', allow_blank=False)
    ws.add_data_validation(validation)
    validation.add(range_address)


def add_validations(wb: Workbook) -> None:
    partition_ws = wb["physical_partitions"]
    add_list_validation(partition_ws, "F2:F100", VALIDATION_LISTS["partition_type"])

    metrics_ws = wb["metrics"]
    add_list_validation(metrics_ws, "C2:C200", VALIDATION_LISTS["subject_type"])
    add_list_validation(metrics_ws, "I2:I200", VALIDATION_LISTS["value_type"])
    add_list_validation(metrics_ws, "L2:L200", VALIDATION_LISTS["confidence"])


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    wb.remove(wb.active)
    for name, rows in SHEETS.items():
        ws = wb.create_sheet(name)
        for row in rows:
            ws.append(row)
        style_sheet(ws)
        add_table(ws, name)
    add_validations(wb)
    wb.save(OUTPUT)
    print(OUTPUT)


if __name__ == "__main__":
    main()
